---
name: cmpsc-302-spring-2019-practical4
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/www/:
    index.html:
        --fragment "<title>" --count 1 --exact
        --fragment "<h1>" --count 1 --exact
        --fragment "<h2>" --count 1 --exact
        --fragment "img src" --count 1 --exact
        --fragment "img/professional_photo.jpg" --count 1 --exact
        --fragment "em em-" --count 2 --exact
        --fragment "fonts.googleapis.com" --count 1 --exact
        --fragment "family=" --count 1 --exact
        --fragment "emoji.css" --count 1 --exact
        --fragment "site.css" --count 1 --exact
        --fragment "<html>" --count 1 --exact
        --fragment "<body>" --count 1 --exact
        --fragment "<footer>" --count 1 --exact
        --fragment "<blockquote>" --count 1 --exact
        --fragment "TODO" --count 0 --exact
src/www/css:
    site.css:
        --fragment "font-family" --count 2
# --> check the number of commits beyond a threshold
--commits 10
# --> check that the linter executes and produces 0 lines of output
--command "htmlhint src/www/index.html" --executes
--command "htmlhint src/www/index.html" --count 1 --exact
--command "htmlhint src/www/index.html" --fragment "no errors found" --count 1 --exact
